- name: Set grafana path
  set_fact:
    grafana_path: "{{ WORKDIR }}/grafana/{{ inventory_hostname }}"

- name: "Cria pasta {{ grafana_path }}"
  file:
    path: "{{ grafana_path }}"
    state: directory
    recurse: yes

- name: Unarchive grafana
  unarchive:
    src: "{{ GRAFANA_BINARY_URL }}"
    dest: "{{ grafana_path }}/"
    remote_src: yes
    creates: "{{ grafana_path }}/grafana"
  register: archive_contents
  when: ansible_distribution == 'MacOSX'

- name: Rename folder
  command: "mv {{ grafana_path }}/grafana-7.1.3 {{ grafana_path }}/grafana"
  ignore_errors: true
  when: ansible_distribution == 'MacOSX'

# - name: Generate Files from Prometheus servers
#   template:
#     src: "prometheus-datasource.json.j2"
#     dest: "/tmp/json/{{ item }}.json"
#   loop: "{{ groups['prometheus'] }}"

# - name: Find json config files
#   find:
#     paths: [/tmp/json/]
#     file_type: file
#     recurse: no
#   register: resultado_find

# - name: Generate datasources
#   shell: "curl --silent --fail --show-error --request POST http://admin:admin@${HOSTNAME}:3000/api/datasources --header 'Content-Type: application/json' --data-binary @{{ item.path }}"
#   with_items: "{{ resultado_find.files }}"
#   ignore_errors: yes

# - name: Cria script de start do kafka exporter
#   template:
#     src: "node-exporter.sh.j2"
#     dest: "{{ grafana_path }}/node-exporter.sh"
#     mode: '0755'