- name: Set grafana path
  set_fact:
    grafana_path: "{{ WORKDIR }}/grafana/{{ inventory_hostname }}"

- name: "Cria pasta {{ grafana_path }}"
  file:
    path: "{{ grafana_path }}"
    state: directory
    recurse: yes

- name: Unarchive grafana
  unarchive:
    src: "{{ DOWNLOAD_DIR }}/grafana.tar.gz"
    dest: "{{ grafana_path }}/"
    remote_src: yes
    creates: "{{ grafana_path }}/grafana-7.1.3"
  register: archive_contents
  when: ansible_distribution == 'MacOSX'

- name: Rename folder
  command: "mv {{ grafana_path }}/grafana-7.1.3 {{ grafana_path }}/grafana"
  ignore_errors: true
  when: ansible_distribution == 'MacOSX'

- name: Generate Files from Prometheus servers
  template:
    src: "prometheus-datasource.json.j2"
    dest: "{{ grafana_path }}/{{ item }}.json"
  loop: "{{ groups['prometheus'] }}"

- name: Cria script de start do grafana
  template:
    src: "grafana.sh.j2"
    dest: "{{ grafana_path }}/grafana.sh"
    mode: '0755'