---

- import_playbook: stop.yml

- hosts: localhost
  gather_facts: no
  tasks: 
  - pause:
      prompt: "A seguinte pasta será apagada: {{ WORKDIR }}. Deseja continuar?"

  - name: "Remove {{ WORKDIR }}"
    file: 
      path: "{{ WORKDIR }}/"
      state: absent
    ignore_errors: true