
groups:
- name: kafka
  rules:
    - alert: Offline_Partiton_Count
      expr: sum(kafka_controller_kafkacontroller_offlinepartitionscount{job="kafka-jmx-exporter"})by(job)  > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: 'Kafka {{ $labels.job }}: {{ $value }} partitons offline'
        description: 'After successful leader election, if the leader for partition dies, then the partition moves to the OfflinePartition state. Offline partitions are not available for reading and writing. Restart the brokers, if needed, and check the logs for errors.'

    - alert: Under_Replicated_Partition_Count
      expr: sum(kafka_server_replicamanager_underreplicatedpartitions{job="kafka-jmx-exporter"})by(job) > 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: 'Kafka {{ $labels.job }}: {{ $value }} under replicated partitons'
        description: 'Under-replicated partitions means that one or more replicas are not available. This is usually because a broker is down.  Restart the broker, and check for errors in the logs.'

    - alert: Active_Controller
      expr: sum(kafka_controller_kafkacontroller_activecontrollercount{job="kafka-jmx-exporter"})by(job) != 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: 'Kafka {{ $labels.job }}: No active controller'
        description: 'No broker in the cluster is reporting as the active controller in the last 1 minute interval. During steady state there should be only one active controller per cluster.'

    - alert: Unclean_Leader_Election
      expr: max(kafka_controller_controllerstats_uncleanleaderelections_total{job="kafka-jmx-exporter"})by(job) != 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: 'Kafka {{ $labels.job }}: {{ $value }} unclean leader elections'
        description: '{{ $value }} unclean partition leader elections in the cluster reported in the last 1 minute interval. When unclean leader election is held among out-of-sync replicas, there is a possibility of data loss if any messages were not synced prior to the loss of the former leader. So if the number of unclean elections is greater than 0, investigate broker logs to determine why leaders were re-elected, and look for WARN or ERROR messages. Consider setting the broker configuration parameter unclean.leader.election.enable to false so that a replica outside of the set of in-sync replicas is never elected leader.'

    - alert: ISR_Expand_Rate
      expr: sum(kafka_server_replicamanager_isrexpands_total{job="kafka-jmx-exporter"})by(job) != 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: 'Kafka {{ $labels.job }}: {{ $value }} ISR Expansion Rate'
        description: 'If a broker goes down, ISR for some of the partitions shrink. When that broker is up again, ISRs are expanded once the replicas are fully caught up. Other than that, the expected value for ISR expansion rate is 0. If ISR is expanding and shrinking frequently, adjust Allowed replica lag.'

    - alert: ISR_Shrink_Rate
      expr: sum(kafka_server_replicamanager_isrshrinks_total{job="kafka-jmx-exporter"})by(job) != 0
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: 'Kafka {{ $labels.job }}: {{ $value }} ISR Shrink Rate'
        description: 'If a broker goes down, ISR for some of the partitions shrink. When that broker is up again, ISRs are expanded once the replicas are fully caught up. Other than that, the expected value for ISR shrink rate is 0. If ISR is expanding and shrinking frequently, adjust Allowed replica lag.'

    - alert: Broker_Count
      expr: count(kafka_server_kafkaserver_brokerstate{job="kafka-jmx-exporter"})by(job) == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: 'Kafka {{ $labels.job }}: No Brokers online!'
        description: 'Broker count is 0'

    - alert: Network_Processor_Idle_Percent
      expr: avg(sum(kafka_network_processor_idlepercent{job="kafka-jmx-exporter"})by(job))by(job) < 0.3
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: 'Kafka {{ $labels.job }}: Network Processor Idle Percent is {{ $value }}!'
        description: 'The average fraction of time the network processors are idle. A lower value {{ $value }} indicates that the network workload of the broker is very high.'

    - alert: Request_Handler_Idle_Percent
      expr: avg(kafka_server_kafkarequesthandlerpool_requesthandleravgidlepercent_count{job="kafka-jmx-exporter"})by(job) < 0.3
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: 'Kafka {{ $labels.job }}: Request Handler Idle Percent is {{ $value }}!'
        description: 'The average fraction of time the request handler threads (IO) are idle. A lower value {{ $value }} indicates that the workload of a broker is very high.'

    - alert: Replica_Fetcher_Manager_Max_Lag
      expr: avg(kafka_server_replicafetchermanager_maxlag{job="kafka-jmx-exporter"})by(job) > 50
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: 'Kafka {{ $labels.job }}: Replica Fetcher Manager Max Lag is {{ $value }}!'
        description: 'The maximum lag between the time that messages are received by the leader replica and by the follower replicas.'

    - alert: Topic_Count
      expr: count(count by (topic,job) (kafka_server_brokertopicmetrics_messagesin_total{job="kafka-jmx-exporter"}))by(job) > 1000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: 'Kafka {{ $labels.job }}: 1000 topics reached'
        description: 'The number of active topics in the cluster has reached 1000.'

    - alert: Request_Queue_Time_Max
      expr: max(rate(kafka_network_requestmetrics_requestqueuetimems_count{job="kafka-jmx-exporter"}[1m])) > 100
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: 'Kafka {{ $labels.job }}: {{ $value }}ms request queue time'
        description: 'Max request queue time exceeded 100ms for a request. It is the time, in milliseconds, that a request currently spends in the request queue.'

    - alert: Response_Queue_Time_Max
      expr: max(rate(kafka_network_requestmetrics_responsequeuetimems_count{job="kafka-jmx-exporter"}[1m])) > 100
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: 'Kafka {{ $labels.job }}: {{ $value }}ms response queue time'
        description: 'Max response queue time exceeded 100ms for a request. It is the length of time, in milliseconds, that the request waits in the response queue.'

    - alert: Zookeeper_Sync_Connect
      expr: avg(kafka_server_sessionexpirelistener_zookeepersyncconnects_total{job="kafka-jmx-exporter"})by(job) < 1
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: 'Kafka {{ $labels.job }}: Zookeeper Sync Disconected'
        description: 'Zookeeper Sync Disconected'

    - alert: KafkaTopicsReplicas
      expr: sum(kafka_topic_partition_in_sync_replica) by (topic) < 3
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Kafka topics replicas (instance {{ $labels.instance }})"
        description: "Kafka topic in-sync partition\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: KafkaConsumersGroup
      expr: sum(kafka_consumergroup_lag) by (consumergroup) > 50
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Kafka consumers group (instance {{ $labels.instance }})"
        description: "Kafka consumers group\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

    - alert: KafkaDown
      expr: up{job="kafka-jmx-exporter"} == 0
      for: 3m
      labels:
        severity: warning
      annotations:
        title: Kafka broker is down
        description: Kafka broker is down on {{ $labels.instance }}. Could not scrape jmx-exporter for 3m.

    - alert: KafkaNoController
      expr: sum(kafka_controller_kafkacontroller_activecontrollercount) < 1
      for: 3m
      labels:
        severity: warning
      annotations:
        title: Kafka cluster has no controller
        description: Kafka controller count < 1, cluster is probably broken.

    - alert: KafkaOfflinePartitions
      expr: sum(kafka_controller_kafkacontroller_offlinepartitionscount) > 0
      for: 3m
      labels:
        severity: warning
      annotations:
        title: Kafka cluster has offline partitions
        description: "{{ $value }} partitions in Kafka went offline (have no leader), cluster is probably broken."

    - alert: KafkaUnderreplicatedPartitions
      expr: sum(kafka_cluster_partition_underreplicated) > 10
      for: 3m
      labels:
        severity: warning
      annotations:
        title: Kafka cluster has underreplicated partitions
        description: "{{ $value }} partitions in Kafka are under replicated"

    - alert: PartitionCountHigh
      expr: max(kafka_server_replicamanager_partitioncount{job="kafka-jmx-exporter"}) by (instance, job) > 100
      for: 3m
      labels:
        severity: alert
      annotations:
        description: 'broker {{ $labels.instance }} has high partition count'


    - alert: UnderReplicatedPartitions
      expr: max(kafka_server_replicamanager_underreplicatedpartitions{job="kafka-jmx-exporter"}) by (instance,job) > 0
      for: 10s
      labels:
        severity: warning
      annotations:
        summary: 'Kafka under replicated partitions'
        description: 'There are {{ $value }} under replicated partitions on {{ $labels.instance }}'
      
    - alert: AbnormalControllerState
      expr: sum(kafka_controller_kafkacontroller_activecontrollercount{job="kafka-jmx-exporter"}) != 1
      for: 10s
      labels:
        severity: warning
      annotations:
        summary: 'Kafka abnormal controller state'
        description: 'There are {{ $value }} active controllers in the cluster'

    - alert: OfflinePartitions
      expr: sum(kafka_controller_kafkacontroller_offlinepartitionscount{job="kafka-jmx-exporter"}) > 0
      for: 10s
      labels:
        severity: warning
      annotations:
        summary: 'Kafka offline partitions'
        description: 'One or more partitions have no leader'

    - alert: UnderMinIsrPartitionCount
      expr: max(kafka_server_replicamanager_underminisrpartitioncount{job="kafka-jmx-exporter"}) by (instance,job) > 0
      for: 10s
      labels:
        severity: warning
      annotations:
        summary: 'Kafka under min ISR partitions'
        description: 'There are {{ $value }} partitions under the min ISR on {{ $labels.instance }}'

    - alert: OfflineLogDirectoryCount
      expr: max(kafka_log_logmanager_offlinelogdirectorycount{job="kafka-jmx-exporter"}) by (instance,job) > 0
      for: 10s
      labels:
        severity: warning
      annotations:
        summary: 'Kafka offline log directories'
        description: 'There are {{ $value }} offline log directories on {{ $labels.instance }}'
    